const GET_CURRENCIES_PENDING = 'GET_CURRENCIES_PENDING'
const GET_CURRENCIES_FULFILLED = 'GET_CURRENCIES_FULFILLED'
const GET_CURRENCIES_REJECTED = 'GET_CURRENCIES_REJECTED'
const GET_HISTORY_PENDING = 'GET_HISTORY_PENDING'
const GET_HISTORY_FULFILLED = 'GET_HISTORY_FULFILLED'
const GET_HISTORY_REJECTED = 'GET_HISTORY_REJECTED'

export {
    GET_CURRENCIES_PENDING,
    GET_CURRENCIES_FULFILLED,
    GET_CURRENCIES_REJECTED,
    GET_HISTORY_PENDING,
    GET_HISTORY_FULFILLED,
    GET_HISTORY_REJECTED,
}